project:
  version: @project.version@
server:
  port: 8082
spring:
  data:
    mongodb:
      database: subscription-management
      uri: mongodb://localhost:27017
subscription:
  swagger:
    baseurl: /